// import { fonts } from "@/styles/fonts";
import { FontType } from "@/types";

// const fonts = [
//   "Sans",
//   "Serif",
//   "Mono",
//   "Open Sans",
//   "Roboto",
//   "DotGothic16",
//   "Montserrat",
//   "Poppins",
//   "Roboto Condensed",
//   "Oswald",
//   "Raleway",
//   "Nunito",
//   "Rubik",
//   "Playfair Display",
//   "Kanit",
//   "Merriweather",
//   "Lora",
//   "Quicksand",
//   "Bebas Neue",
//   "Libre Franklin",
//   "Josefin Sans",
//   "Libre Baskerville",
//   "Arimo",
//   "Source Code Pro",
//   "Dosis",
//   "Dancing Script",
//   "Figtree",
//   "Crimson Text",
//   "EB Garamond",
//   "Bitter",
//   "Fira Sans Condensed",
//   "Anton",
//   "Abel",
//   "Barlow Condensed",
//   "Space Grotesk",
//   "Exo",
//   "Teko",
//   "Oxygen",
//   "Red Hat Display",
//   "Pacifico",
//   "Lexend",
//   "Comfortaa",
//   "Caveat",
//   "Cormorant Garamond",
//   "archivo Black",
//   "Arvo",
//   "Lilita One",
//   "Shadows Into Light",
//   "Satisfy",
//   "Permanent Marker",
//   "Abril Fatface",
//   "Play",
//   "Indie Flower",
//   "Spicy Rice",
//   "Urbanist",
//   "Cinzel Decorative",
//   "Vollkorn",
//   "Marcellus",
//   "Saira Condensed",
//   "Concert One",
//   "Tinos",
//   "Great Vibes",
//   "Francois One",
//   "Orbitron",
//   "Amatic SC",
//   "Montserrat Alternates",
//   "Oleo Script",
//   "Rubik Mono One",
//   "Creepster",
//   "Silkscreen",
//   "Pirata One",
//   "Yellowtail",
//   "Sixtyfour",
//   "Crete Round",
//   "Courgette",
//   "Gloria Hallelujah",
//   "Bodoni Moda",
//   "Mate SC",
//   "Sacramento",
//   "Old Standard TT",
//   "Philosopher",
//   "Yatra One",
//   "Gruppo",
//   "Macondo",
//   "Neucha",
//   "Zeyada",
//   "Itim",
//   "Allura",
//   "Poiret One",
//   "Advent Pro",
//   "Sofia",
//   "Patrick Hand",
//   "Syne",
//   "Sarpanch",
//   "Tangerine",
//   "Architects Daughter",
//   "Special Elite",
//   "Epilogue",
//   "Cuprum",
//   "Literata",
//   "Fira Sans Extra Condensed",
//   "Pathway Gothic One",
//   "Yeseva One",
//   "Playfair Display SC",
//   "Bungee",
//   "Parisienne",
//   "Comic Neue",
//   "Jura",
//   "Handlee",
//   "Reenie Beanie",
//   "Faustina",
//   "Forum",
//   "Homemade Apple",
//   "Sriracha",
//   "VT323",
//   "League Gothic",
//   "Alex Brush",
//   "Antonio",
//   "Arsenal",
//   "Nothing You Could Do",
//   "Six Caps",
//   "Nanum Pen Script",
//   "Bad Script",
//   "Unica One",
//   "Monoton",
//   "Alegreya Sans SC",
//   "Syncopate",
//   "Rock Salt",
//   "Quantico",
//   "Big Shoulders Display",
//   "Viga",
//   "Averia Serif Libre",
//   "Economica",
//   "Darker Grotesque",
//   "Covered By Your Grace",
//   "Berkshire Swash",
//   "Days One",
//   "Mrs Saint Delafield",
//   "Gochi Hand",
//   "Charm",
//   "Just Another Hand",
//   "Corben",
//   "Allison",
//   "Laila",
//   "Palanquin",
//   "Herr Von Muellerhoff",
//   "La Belle Aurore",
//   "Delius",
//   "Kiwi Maru",
//   "Marcellus SC",
//   "Gowun Batang",
//   "Fredericka the Great",
//   "Italiana",
//   "Shantell Sans",
//   "Nixie One",
//   "Ms Madi",
//   "Klee One",
//   "Yesteryear",
//   "Limelight",
//   "Petit Formal Script",
//   "Bokor",
//   "Love Ya Like A Sister",
//   "Waiting for the Sunrise",
//   "Quintessential",
//   "Dawning of a New Day",
//   "Grenze Gotisch",
//   "Fanwood Text",
//   "Ephesis",
//   "Koho",
//   "Gotu",
//   "Imbue",
//   "Over the Rainbow",
//   "Pompiere",
//   "Aboreto",
//   "Major Mono Display",
//   "Notable",
//   "Square Peg",
//   "IM Fell English SC",
//   "Aladin",
//   "Hurricane",
//   "Quando",
//   "Fondamento",
//   "Sue Ellen Francisco",
//   "Federo",
//   "League Script",
//   "Meow Script",
//   "Just Me Again Down Here",
//   "Gugi",
//   "Elsie",
//   "Supermercado One",
//   "Happy Monkey",
//   "Iceberg",
//   "Vast Shadow",
//   "Walter Turncoat",
//   "Sofadi One",
//   "Kalnia",
//   "Numans",
//   "Bilbo Swash Caps",
//   "Charmonman",
//   "Bubbler One",
//   "Carme",
//   "Amarante",
//   "Metamorphous",
//   "Gaegu",
//   "Uncial Antiqua",
//   "The Girl Next Door",
//   "Wire One",
//   "Grape Nuts",
//   "WindSong",
//   "Jacquard 24",
//   "Delius Unicase",
//   "Cherry Swash",
//   "Hachi Maru Pop",
//   "Swanky and Moo Moo",
//   "Glass Antiqua",
//   "Fontdiner Swanky",
//   "Lobster Two",
// ];

export const mainFonts: FontType[] = [
  { key: "font-sans", value: "sans", label: "Sans" },
  { key: "font-serif", value: "serif", label: "Serif" },
  { key: "font-mono", value: "mono", label: "Mono" },
];

// export const otherFonts: FontType[] = fonts.map((font) =>
//   Object.assign({
//     key: `font-${font.split(" ").join("-").toLowerCase()}`,
//     value: font.split(" ").join("-").toLowerCase(),
//     label: font,
//   }),
// );

// export const otherFonts: FontType[] = Object.values(fonts).map((font) =>
//   Object.assign({
//     key: font.className,
//     value: font.style.fontFamily
//       .split("'")[1]
//       .split("_")
//       .slice(2,  1)
//       .join(" ")
//       .toLowerCase(),
//     label: font.style.fontFamily
//       .split("'")[1]
//       .split("_")
//       .slice(0,  1)
//       .join(" "),
//   }),
// );
