import { SVGProps } from "react";

export type IconSvgProps = SVGProps<SVGSVGElement> & {
  size?: number;
};

export interface ColorProps {
  bgColor: string[];
  setBgColor: React.Dispatch<React.SetStateAction<string[]>>;
  setTextColor: React.Dispatch<React.SetStateAction<string>>;
  textColor: string;
}

export type ColorParams = "bg" | "text";
export type WeekdayParams = "start" | "week-label" | "week-font" | "week-size";
export type MonthParams = "month-label" | "month-font" | "month-size";
export type YearParams = "year-label";
export type WallpaperParams = "ratio" | "size";
export type QueryParams =
  | "date"
  | ColorParams
  | WeekdayParams
  | MonthParams
  | YearParams
  | WallpaperParams;

export type WeekdayStart = "0" | "1";

// export type WeekdayLabel = "short" | "long" | "full";
export type WeekdayLabel = "long" | "short" | "narrow";
export type MonthLabel = "numeric" | "2-digit" | "long" | "short" | "narrow";
export type YearLabel = "show" | "hide";

export type WallpaperQuality = "4K" | "QHD" | "FHD" | "HD" | "SD";

export type AspectRatio =
  | "16:9"
  | "9:16"
  // | "5:4"
  // | "4:5"
  // | "7:5"
  // | "5:7"
  // | "4:3"
  // | "3:4"
  // | "5:3"
  // | "3:5"
  // | "3:2"
  // | "2:3"
  | "1:1";

export type WxH = { width: number; height: number };

export type Sizes = {
  [Ratio in AspectRatio]: WxH[];
};

export type Font = "Sans" | "Serif" | "Mono";

// export type OtherFont =
//   | "Abel"
//   | "Aboreto"
//   | "Abril Fatface"
//   | "Advent Pro"
//   | "Aladin"
//   | "Alegreya Sans SC"
//   | "Alex Brush"
//   | "Allison"
//   | "Allura"
//   | "Amarante"
//   | "Amatic SC"
//   | "Anton"
//   | "Antonio"
//   | "Architects Daughter"
//   | "Archivo Black"
//   | "Arimo"
//   | "Arsenal"
//   | "Arvo"
//   | "Averia Serif Libre"
//   | "Bad Script"
//   | "Barlow Condensed"
//   | "Bebas Neue"
//   | "Berkshire Swash"
//   | "Big Shoulders Display"
//   | "Bilbo Swash Caps"
//   | "Bitter"
//   | "Bodoni Moda"
//   | "Bokor"
//   | "Bubbler One"
//   | "Bungee"
//   | "Carme"
//   | "Caveat"
//   | "Charm"
//   | "Charmonman"
//   | "Cherry Swash"
//   | "Cinzel Decorative"
//   | "Comfortaa"
//   | "Comic Neue"
//   | "Concert One"
//   | "Corben"
//   | "Cormorant Garamond"
//   | "Courgette"
//   | "Covered By Your Grace"
//   | "Creepster"
//   | "Crete Round"
//   | "Crimson Text"
//   | "Cuprum"
//   | "Dancing Script"
//   | "Darker Grotesque"
//   | "Dawning of a New Day"
//   | "Days One"
//   | "Delius"
//   | "Delius Unicase"
//   | "Dosis"
//   | "DotGothic16"
//   | "EB Garamond"
//   | "Economica"
//   | "Elsie"
//   | "Ephesis"
//   | "Epilogue"
//   | "Exo"
//   | "Fanwood Text"
//   | "Faustina"
//   | "Federo"
//   | "Figtree"
//   | "Fira Sans Condensed"
//   | "Fira Sans Extra Condensed"
//   | "Fondamento"
//   | "Fontdiner Swanky"
//   | "Forum"
//   | "Francois One"
//   | "Fredericka the Great"
//   | "Gaegu"
//   | "Glass Antiqua"
//   | "Gloria Hallelujah"
//   | "Gochi Hand"
//   | "Gotu"
//   | "Gowun Batang"
//   | "Grape Nuts"
//   | "Great Vibes"
//   | "Grenze Gotisch"
//   | "Gruppo"
//   | "Gugi"
//   | "Hachi Maru Pop"
//   | "Handlee"
//   | "Happy Monkey"
//   | "Herr Von Muellerhoff"
//   | "Homemade Apple"
//   | "Hurricane"
//   | "Iceberg"
//   | "IM Fell English SC"
//   | "Imbue"
//   | "Indie Flower"
//   | "Italiana"
//   | "Itim"
//   | "Jacquard 24"
//   | "Josefin Sans"
//   | "Jura"
//   | "Just Another Hand"
//   | "Just Me Again Down Here"
//   | "Kalnia"
//   | "Kanit"
//   | "Kiwi Maru"
//   | "Klee One"
//   | "KoHo"
//   | "La Belle Aurore"
//   | "Laila"
//   | "League Gothic"
//   | "League Script"
//   | "Lexend"
//   | "Libre Baskerville"
//   | "Libre Franklin"
//   | "Lilita One"
//   | "Limelight"
//   | "Literata"
//   | "Lobster Two"
//   | "Lora"
//   | "Love Ya Like A Sister"
//   | "Macondo"
//   | "Major Mono Display"
//   | "Marcellus"
//   | "Marcellus SC"
//   | "Mate SC"
//   | "Meow Script"
//   | "Merriweather"
//   | "Metamorphous"
//   | "Monoton"
//   | "Montserrat"
//   | "Montserrat Alternates"
//   | "Mrs Saint Delafield"
//   | "Ms Madi"
//   | "Nanum Pen Script"
//   | "Neucha"
//   | "Nixie One"
//   | "Notable"
//   | "Nothing You Could Do"
//   | "Numans"
//   | "Nunito"
//   | "Old Standard TT"
//   | "Oleo Script"
//   | "Open Sans"
//   | "Orbitron"
//   | "Oswald"
//   | "Over the Rainbow"
//   | "Oxygen"
//   | "Pacifico"
//   | "Palanquin"
//   | "Parisienne"
//   | "Pathway Gothic One"
//   | "Patrick Hand"
//   | "Permanent Marker"
//   | "Petit Formal Script"
//   | "Philosopher"
//   | "Pirata One"
//   | "Play"
//   | "Playfair Display"
//   | "Playfair Display SC"
//   | "Poiret One"
//   | "Pompiere"
//   | "Poppins"
//   | "Quando"
//   | "Quantico"
//   | "Quicksand"
//   | "Quintessential"
//   | "Raleway"
//   | "Red Hat Display"
//   | "Reenie Beanie"
//   | "Roboto"
//   | "Roboto Condensed"
//   | "Rock Salt"
//   | "Rubik"
//   | "Rubik Mono One"
//   | "Sacramento"
//   | "Saira Condensed"
//   | "Sarpanch"
//   | "Satisfy"
//   | "Shadows Into Light"
//   | "Shantell Sans"
//   | "Silkscreen"
//   | "Six Caps"
//   | "Sixtyfour"
//   | "Sofadi One"
//   | "Sofia"
//   | "Source Code Pro"
//   | "Space Grotesk"
//   | "Special Elite"
//   | "Spicy Rice"
//   | "Square Peg"
//   | "Sriracha"
//   | "Sue Ellen Francisco"
//   | "Supermercado One"
//   | "Swanky and Moo Moo"
//   | "Syncopate"
//   | "Syne"
//   | "Tangerine"
//   | "Teko"
//   | "The Girl Next Door"
//   | "Tinos"
//   | "Uncial Antiqua"
//   | "Unica One"
//   | "Urbanist"
//   | "Vast Shadow"
//   | "Viga"
//   | "Vollkorn"
//   | "VT323"
//   | "Waiting for the Sunrise"
//   | "Walter Turncoat"
//   | "WindSong"
//   | "Wire One"
//   | "Yatra One"
//   | "Yellowtail"
//   | "Yeseva One"
//   | "Yesteryear"
//   | "Zeyada";
export type FontType = { key: string; value: string; label: Font };
